# Cloud Build configuration for automated deployments
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/futuregolf-backend:$COMMIT_SHA', '.']
    dir: 'backend'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/futuregolf-backend:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'futuregolf-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/futuregolf-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/futuregolf-backend:$COMMIT_SHA'

# Set timeout for the entire build
timeout: '1200s'